package com.practice.java8.functionalinterfaces.bankApplication.methodReference;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.function.BiFunction;

public class Main2 {

        public static void main(String[] args) {

            Invoice obj = new Invoice("A001", BigDecimal.valueOf(1.99), 3);

            InvoiceCalculator formula = new InvoiceCalculator();

            // lambda
            BigDecimal result = calculate(formula, obj, (f, o) -> f.normal(o));         // 5.97
            System.out.println(result);

            // method reference
            BigDecimal result2 = calculate(formula, obj, InvoiceCalculator::normal);    // 5.97
            System.out.println(result2);

            // lambda
            BigDecimal result3 = calculate(formula, obj, (f, o) -> f.promotion(o));     // 5.37
            System.out.println(result3);

            // method reference
            BigDecimal result4 = calculate(formula, obj, InvoiceCalculator::promotion); // 5.37
            System.out.println(result4);

        }

        static BigDecimal calculate(InvoiceCalculator formula, Invoice s1,
                                    BiFunction<InvoiceCalculator, Invoice, BigDecimal> func) {
            return func.apply(formula, s1);
        }

    }

    class InvoiceCalculator {

        public BigDecimal normal(Invoice obj) {
            return obj.getUnitPrice().multiply(BigDecimal.valueOf(obj.qty));
        }

        public BigDecimal promotion(Invoice obj) {
            return obj.getUnitPrice()
                    .multiply(BigDecimal.valueOf(obj.qty))
                    .multiply(BigDecimal.valueOf(0.9))
                    .setScale(2, RoundingMode.HALF_UP);
        }
    }

    class Invoice {

        String no;

        public Invoice(String no, BigDecimal unitPrice, Integer qty) {
            this.no = no;
            this.unitPrice = unitPrice;
            this.qty = qty;
        }

        public String getNo() {
            return no;
        }

        public void setNo(String no) {
            this.no = no;
        }

        public BigDecimal getUnitPrice() {
            return unitPrice;
        }

        public void setUnitPrice(BigDecimal unitPrice) {
            this.unitPrice = unitPrice;
        }

        public Integer getQty() {
            return qty;
        }

        public void setQty(Integer qty) {
            this.qty = qty;
        }

        BigDecimal unitPrice;
        Integer qty;

        // generated by IDE, setters, gettes, constructor, toString
    }

